name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd energy-forecasting-ml-system || git clone https://github.com/sohel10/energy-forecasting-ml-system.git

          cd energy-forecasting-ml-system

          git pull

          docker stop energy-app || true
          docker rm energy-app || true

          docker build -t energy-app .

          docker run -d -p 8000:8000 energy-app